from pysaber.saber_params import (SABER_BYTES_CCA_DEC, SABER_KEYBYTES, SABER_L,
                                  SABER_PUBLICKEYBYTES, SABER_SECRETKEYBYTES)

if SABER_L == 2:
    CRYPTO_ALGNAME = "LightSaber"
elif SABER_L == 3:
    CRYPTO_ALGNAME = "Saber"
elif SABER_L == 4:
    CRYPTO_ALGNAME = "FireSaber"
else:
    raise ValueError("Unsupported SABER parameter.")


CRYPTO_SECRETKEYBYTES = SABER_SECRETKEYBYTES
CRYPTO_PUBLICKEYBYTES = SABER_PUBLICKEYBYTES
CRYPTO_BYTES = SABER_KEYBYTES
CRYPTO_CIPHERTEXTBYTES = SABER_BYTES_CCA_DEC
