# Security strengths similar to: AES-128, AES-192, AES-256

# SABER_L = 2  # LightSaber
SABER_L = 3  # Saber
# SABER_L = 4  # FireSaber


if SABER_L == 2:
    SABER_MU = 10
    SABER_ET = 3
elif SABER_L == 3:
    SABER_MU = 8
    SABER_ET = 4
elif SABER_L == 4:
    SABER_MU = 6
    SABER_ET = 6

SABER_EQ = 13
SABER_EP = 10
SABER_N = 256

SABER_SEEDBYTES = 32
SABER_NOISE_SEEDBYTES = 32
SABER_KEYBYTES = 32
SABER_HASHBYTES = 32

SABER_POLYCOINBYTES = (SABER_MU * SABER_N // 8)

SABER_POLYBYTES = (SABER_EQ * SABER_N // 8)
SABER_POLYVECBYTES = (SABER_L * SABER_POLYBYTES)

SABER_POLYCOMPRESSEDBYTES = (SABER_EP * SABER_N // 8)
SABER_POLYVECCOMPRESSEDBYTES = (SABER_L * SABER_POLYCOMPRESSEDBYTES)

SABER_SCALEBYTES_KEM = (SABER_ET * SABER_N // 8)

SABER_INDCPA_PUBLICKEYBYTES = (SABER_POLYVECCOMPRESSEDBYTES + SABER_SEEDBYTES)
SABER_INDCPA_SECRETKEYBYTES = (SABER_POLYVECBYTES)

SABER_PUBLICKEYBYTES = SABER_INDCPA_PUBLICKEYBYTES
SABER_SECRETKEYBYTES = (SABER_INDCPA_SECRETKEYBYTES + SABER_INDCPA_PUBLICKEYBYTES + SABER_HASHBYTES + SABER_KEYBYTES)

SABER_BYTES_CCA_DEC = (SABER_POLYVECCOMPRESSEDBYTES + SABER_SCALEBYTES_KEM)
